### ISSUE TITLE
Allow transition on initial rendering

### ISSUE THREAD

**Issue by FrancoisCamus** [adopted-ember-addons/ember-collapsible-panel#21] opened 2016-09-22 09:19 UTC
At the moment the first click to toggle does not animate the body. I stopped using this addon and wrote a custom component for this reason.

You should use a transition instead of the `use` option like this:

```
export default function() {
  this.transition(
    this.includingInitialRender(),
    this.hasClass('some-body'),
    this.use('crossFade')
  );
}
```

**Comment by samselikoff** [comment] 2016-10-01 16:10
Hm - when I open the [demo page](http://tedconf.github.io/ember-collapsible-panel/) and click on the first panel, it animates open. Could you reproduce, in a Twiddle perhaps? Or describe the steps to reproduce?

**Comment by FrancoisCamus** [comment] 2016-10-17 14:52
I think the problem arises when rendering components in the panel body. In my case I was rendering a grid with multiple lines. I checked the demo page and there is only static content in the panel bodies.

**Comment by samselikoff** [comment] 2016-10-19 00:03
I see... I think the solution here is to add support for custom (host app-defined) transitions. Then, you could provide your own transition to use. Would that solve the problem?

Also, I agree it would be nice if the default transition worked for components, so that's something else we could tackle.

**Comment by FrancoisCamus** [comment] 2017-02-13 10:15
Yes that would be a great feature.

**Comment by samselikoff** [comment] 2017-03-06 17:57
@FrancoisCamus could you help with this feature? First we need to brianstorm the API.

Liquid Fire already has a way to define custom animations so we just need a way to (1) specify specific animations on a per-panel basis and (2) specify a new default

**Comment by MelSumner** [comment] 2022-02-07 00:36
I'm going to close this issue merely due to age. If it's still an issue, please re-open. Thank you! 👍

**Closed as completed by MelSumner** 2022-02-07 00:36 UTC
