### ISSUE TITLE
dependency-checker can't find dependencies when cp-panel installed via addon

### ISSUE THREAD

**Issue by crodriguez1a** [adopted-ember-addons/ember-collapsible-panel#20] opened 2016-09-01 15:13 UTC
I'll try to explain as best as I can but essentially our app is composed like this:
- consuming app
  - component library add-on
    - ember-collapsible-panel
    - a bunch of other components

The `dependency-checker` service appears to be looking at the consuming applications environment for the add-on `ENV['ember-collapsible-panel']`, and not the add-on with which it was bootstrapped. 

Currently, I've been able to get around this simply by installing the add-on at the consuming application.

@samselikoff Great add-on. Some very cool patterns in here.

**Comment by samselikoff** [comment] 2016-09-01 17:20
https://github.com/tedconf/ember-collapsible-panel/issues/19 had a similar problem, maybe we need to move `dpenedency-checker` into `dependencies`

Could you fork this project, move `ember-cli-dependency-checker` from the `"devDependencies"` key to the `"dependencies"` key, and see if it works in your local project?

**Comment by crodriguez1a** [comment] 2016-09-01 20:06
@samselikoff Will do. I'll let you know. Thanks!

**Comment by crodriguez1a** [comment] 2016-09-01 23:01
@samselikoff That doesn't seem to work. As referenced in #19, the error happens because `ENV['ember-collapsible-panel']` is `undefined`. Was ember-cli-dependency-checker supposed have added `ember-collapsible-panel` as a property of ENV? In any case, let me know what else I can do to help.

**Comment by samselikoff** [comment] 2016-09-03 11:46
Ohh I see. I think we need to set a default `{}` for the ENV options.

Could you try adding something similar to [this line](https://github.com/samselikoff/ember-cli-mirage/blob/master/index.js#L30) to set the default in your fork, and see if that fixes it? I think it will just be adding

``` js
this.app.project.config(app.env)['ember-collapsible-panel'] || {};
```

in the `included` part of this addon's `index.js`.

**Comment by crodriguez1a** [comment] 2016-09-04 12:43
@samselikoff No luck. I'm pretty sure the `environment.js` from within `ember-collapsible-panel`'s config never gets executed. That logic seemingly is always overridden by `environment.js` in the consuming add-on and subsequently the consuming app. 

Even from the add-on layer, if I return anything at all from `environment.js`, it will override `ember-collapsible-panel`'s `environment.js`

I wonder if there is some existing protocol for carrying that logic all the way up?

**Comment by samselikoff** [comment] 2016-09-08 03:17
Can I see your app's and your addon's `package.json`?

**Comment by samselikoff** [comment] 2016-09-08 03:21
Ok I've reproduced the problem locally. Working on it

**Comment by samselikoff** [comment] 2016-09-08 04:14
I'm looking at ember-moment and they share host-app config differently: https://github.com/stefanpenner/ember-moment/blob/2604572ad57ac34d4c8e7643a70477ce89a612f4/app/helpers/moment-to-date.js

I'm wondering if we should move the config stuff there (somewhere under `/app`) so this addon works even if it's nested.

**Comment by crodriguez1a** [comment] 2016-09-12 14:38
@samselikoff Hm...that sounds promising. I'll give that a try.

**Comment by jbailey4** [comment] 2017-05-27 12:26
@samselikoff Can confirm what @crodriguez1a is seeing. I'm noticing the `config` cli hook never gets invoked for nested addons. So, ember-collapsible-panel never has a chance to [setup its configuration](https://github.com/tedconf/ember-collapsible-panel/blob/master/index.js#L10-L18). This leads to [`app/services/dependency-checker.js`](https://github.com/tedconf/ember-collapsible-panel/blob/master/index.js#L10-L18) throwing an error, since `ENV['ember-collapsible-panel']` would be `undefined`.

Have you looked into this anymore?

I have a couple thoughts:

1. Move the check for liquid-fire at runtime, instead of depending on build configuration variables. This would work no matter how nested the addon is.
2. Utilize the `included` cli hook in some way to build the configuration. The `included` hook seems to always be called no matter how nested the addon is, and this hook gets access to the parent app.

**Comment by MelSumner** [comment] 2022-02-07 00:36
I'm going to close this issue merely due to age. If it's still an issue, please re-open. Thank you! 👍

**Closed as completed by MelSumner** 2022-02-07 00:36 UTC
